version: "3"

services:
  poker:
    build:
      context: ..
      dockerfile: deployments/poker.Dockerfile
    image: poker:latest
    environment:
      LOG_LEVEL: debug

  lavris:
    build:
      context: ..
      dockerfile: deployments/larvis.Dockerfile
    image: lavris:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      LOG_LEVEL: debug