linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  gocritic:
    color: true
    shorterErrLocation: true

    enabled-tags:
      - performance
      - style
      - experimental

    disabled-checks:
      - hugeParam

linters:
  enable:
    - golint
    - megacheck
    - interfacer
    - unconvert
    - goconst
    - misspell
    - unparam
    - gofmt
    - gocyclo
    - gocritic
    - govet
    - unused
  disable:
    - gas

issues:
  exclude-use-default: false
max-same-issues: 10
