apiVersion: apps/v1
kind: Deployment
metadata:
  name: larvis
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: larvis
  template:
    metadata:
      labels:
        app: larvis
    spec:
      containers:
        - name: lavris
          image: lavris:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "300Mi"
              cpu: "0.3"
            requests:
              memory: "100Mi"
              cpu: "0.1"
          env:
            - name: ADDR
              value: "8080"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3600
            periodSeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: larvis-svc
  namespace: dev
spec:
  selector:
    app: larvis
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  externalName: larvis
